[package]
name = "better_lua"
version = "0.0.1"
description = "better lua"
edition = "2021"

[dependencies]
memchr = "2.5"
bytecount = "0.6"
debug_tree = "0.4"
# 0.9.5 fails on luajit vendored
mlua = { version = "0.9.4", features = ["luajit", "vendored"] }
