[package]
name = "luis"
version = "0.1.1"
authors = ["Steve Dignam <steve@dignam.xyz>"]
description = "a Lua parser in Rust"
license = "AGPL-3.0"
readme="README.md"
repository = "https://github.com/sbdchd/luis"

[dependencies]
